JDP210401-2 testowy GroupControler
interceptor2048/projekt-jdp-2104-01 pull request #3
Opened 2021-04-30 12:06 UTC by TomekSzaty

…z implementacją endpointów , zwrac…ającą sztuczne dane

2021-05-01 12:59 UTC, OskarAnczyk requested changes
_values_ in adnotation RequestMapping should be the same as method name to avoid confusion during tests.

2021-05-02 16:34 UTC, anna850412 approved these changes

2021-05-02 21:22 UTC, WojtekSJ commented
> …z implementacją endpointów , zwrac…ającą sztuczne dane



> _values_ in adnotation RequestMapping should be the same as method name to avoid confusion during tests.

Agree to keep the same Mapping names as method names. When change will be implemented can be merged to master.

2021-05-04 18:13 UTC, WojtekSJ approved these changes

2021-05-04 18:47 UTC, merged